<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE spec [
    <!ELEMENT spec (auxfiles?, name, toc)>
    <!ATTLIST spec id CDATA #REQUIRED>
    <!ATTLIST spec variant CDATA #REQUIRED>
    <!ATTLIST spec revision CDATA #REQUIRED>
    <!ATTLIST spec lang CDATA #REQUIRED>
    <!ATTLIST spec version CDATA #REQUIRED>
    <!ATTLIST spec xmlns CDATA #FIXED "http://apple.com/ns/spec/v1">
    <!ATTLIST spec accsys CDATA #FIXED "http://apple.com/ns/accsys/v1">
    <!ELEMENT auxfiles (file)*>
    <!ELEMENT file EMPTY>
    <!ATTLIST file type CDATA #FIXED "pdf">
    <!ATTLIST file verifier CDATA #REQUIRED>
    <!ATTLIST file read-info CDATA #IMPLIED>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT toc (entry)+>
    <!ELEMENT entry (index, name, keywords?, related*, internal?)>
    <!ATTLIST entry label CDATA #REQUIRED>
    <!ATTLIST entry type (section|chapter|figure|table) "section">
    <!ELEMENT index (#PCDATA)>
    <!ELEMENT internal (#PCDATA)>
    <!ELEMENT related (item)*>
    <!ELEMENT item (#PCDATA)>
    <!ELEMENT keywords (#PCDATA)>
]>
<spec revision="27" id="aispec" lang="en-US" accsys="http://apple.com/ns/accsys/v1" variant="release" version="1" xmlns="http://apple.com/ns/spec/v1">
<auxfiles>
<file type="pdf" verifier="Accessory,Interface,Specification,Release,R27" read-info="52,42,508,700">
</file>
</auxfiles>
<name>Accessory Interface Specification R27</name>
<toc>
<entry label="Introduction" type="chapter">
<index>1</index>
<name>Introduction</name>
<keywords>aforementioned,cryptography,computation,possibility,challenging,explicitly,television,creation,watchos,philip</keywords>
<related>
<item>featureAirPlay:Introduction</item>
<item>componentAuthCP3.0:Registers:Descriptions:AuthenticationControlAndStatus:WriteOnlyBits</item>
<item>Introduction:Terminology</item>
<item>Introduction:Terminology:AccessoryDeviceProduct</item>
<item>Introduction:Terminology:Challenge</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11CLK0001</internal>
</entry>
<entry label="Introduction:Purpose" type="section">
<index>1.1</index>
<name>Purpose of This Specification</name>
<keywords>recommendation,purpose,tv,watch,detail,requirement,interface,connector,apple,device</keywords>
<related>
<item>RevisionHistory:UpdatedContent</item>
<item>connectorE75:Versions</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0002</internal>
</entry>
<entry label="Introduction:Organization" type="section">
<index>1.2</index>
<name>Organization</name>
<keywords>related,chapter,tool,group,part,component,transport,protocol,feature,module</keywords>
<related>
<item>transportUSB:HostMode:Enumeration</item>
<item>CarPlayParameterValueTable:enum:featuresCarPlay:SpeechModes</item>
<item>Introduction:Terminology:AuthenticationCoprocessor</item>
<item>protocoliAP2:Link:LinkSynchronizationPayload:iAP2Sessions</item>
<item>connectorE75:Versions</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0003</internal>
</entry>
<entry label="Introduction:Applicability" type="section">
<index>1.3</index>
<name>Applicability</name>
<keywords>trackpad,magic,accessory interface,apple watch series,conflict,ipad air,cover,generation</keywords>
<related>
<item>RevisionHistory:UpdatedContent</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0004</internal>
</entry>
<entry label="Introduction:Requirements" type="section">
<index>1.4</index>
<name>Requirements, Recommendations, and Permissions</name>
<keywords>implication,prohibition,historical,statement,understand,permission,approval,meaning,absence</keywords>
<related>
<item>protocoliAP2:Link:Examples:iAP2LinkPacketStructure</item>
<item>featureAccessoryPower:Usage:EnteringIntermittentHighPowerMode</item>
<item>featureCarPlay:GeneralRequirements:Architecture:CarPlayOverWireless:Frequency Bands</item>
<item>featuresAccessoryPower:Usage</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0005</internal>
</entry>
<entry label="Introduction:DeveloperPreview" type="section">
<index>1.5</index>
<name>Developer Preview</name>
<keywords>adoption,licensed,final,accuracy,preview,propose,developer,subject</keywords>
<related>
<item>accessoryCables:USBCToUltra</item>
<item>accessoryCables:USBAToUltra</item>
<item>accessoryCables:E75ToUltra</item>
<item>accessoryCables:HeadsetPlugToUltra</item>
<item>accessoryCables:Headset:MikeyBusAccessory</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0006</internal>
</entry>
<entry label="Introduction:ManufacturerPreview" type="section">
<index>1.6</index>
<name>Manufacturer Preview</name>
<keywords>develop,preview,license,propose,final,manufacturer,applicable,content,developer</keywords>
<related>
<item>toolRoswellBreakoutBoards</item>
<item>toolATSMikeyBusBox</item>
<item>moduleC101P</item>
<item>toolATSC71Box</item>
<item>protocoliAP2:Link:LinkSynchronizationPayload:MaximumPacketLength</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0007</internal>
</entry>
<entry label="Introduction:Terminology" type="section">
<index>1.7</index>
<name>Terminology</name>
<keywords>aforementioned,cryptography,possibility,computation,challenging,explicitly,television,creation,watchos,philip</keywords>
<related>
<item>accessoryAll:TestProcedures:OTA:Terminology</item>
<item>componentAuthCP3.0:Registers:Descriptions:AuthenticationControlAndStatus:WriteOnlyBits</item>
<item>Introduction</item>
<item>Introduction:Terminology:AccessoryDeviceProduct</item>
<item>Introduction:Terminology:Challenge</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0008</internal>
</entry>
<entry label="Introduction:Terminology:AccessoryDeviceProduct" type="section">
<index>1.7.1</index>
<name>Accessory, Device, and Product</name>
<keywords>aforementioned,television,explicitly,watchos,term,mobile,statement,operate</keywords>
<related>
<item>Introduction</item>
<item>Introduction:Terminology</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0009</internal>
</entry>
<entry label="Introduction:Terminology:AuthenticationCoprocessor" type="section">
<index>1.7.2</index>
<name>Authentication Coprocessor</name>
<keywords>creation,related,signature,verification,coprocessor,hardware,digital,authentication,component,service</keywords>
<related>
<item>transportUSB:HostMode:Enumeration</item>
<item>Introduction:Organization</item>
<item>featureCarPlay:CarPlayCommunicationProtocol:SetupandControl:MFI-SAP</item>
<item>CarPlayParameterValueTable:enum:featuresCarPlay:SpeechModes</item>
<item>Introduction</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0010</internal>
</entry>
<entry label="Introduction:Terminology:I2CBus" type="section">
<index>1.7.3</index>
<name>I2C Bus</name>
<keywords>philip,al,reside,easy,document,locate,circuit,bus,board,wire</keywords>
<related>
<item>moduleX533:I2CInterfaceAddressing</item>
<item>featureAirPlay:UserrequirementsforusingAirPlay:Network</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0011</internal>
</entry>
<entry label="Introduction:Terminology:Challenge" type="section">
<index>1.7.4</index>
<name>Challenge</name>
<keywords>challenging,computation,vice,random,verification,offer,return,result,response,perform</keywords>
<related>
<item>Introduction:Terminology:ChallengeResponse</item>
<item>componentAuthCP3.0:Registers:Descriptions:AuthenticationControlAndStatus:WriteOnlyBits</item>
<item>Introduction</item>
<item>Introduction:Terminology</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0012</internal>
</entry>
<entry label="Introduction:Terminology:ChallengeResponse" type="section">
<index>1.7.5</index>
<name>Challenge Response</name>
<keywords>obtain,challenge,offer,response,result,process,perform,page</keywords>
<related>
<item>Introduction:Terminology:Challenge</item>
<item>componentAuthCP20C:Registers:Descriptions:ChallengeResponseData</item>
<item>featureSiri:ObtainingSiriAvailabilityInformation</item>
<item>componentAuthCP3.0:ChallengeData</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0013</internal>
</entry>
<entry label="Introduction:Terminology:X509Certificate" type="section">
<index>1.7.6</index>
<name>X.509 Certificate</name>
<keywords>cryptography,telecommunication,govern,international,public,identity,union,verification,certificate,sender</keywords>
<related>
<item>featureCarPlay:GeneralRequirements:MediaTypesandFormats:Audio:Telephony</item>
<item>protocolA2DP:MPEG24AACCodecs</item>
<item>featureCarPlay:GeneralRequirements:HardwareRequirements:ConnectiontoAppleDevice</item>
<item>Introduction</item>
<item>Introduction:Terminology</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0014</internal>
</entry>
<entry label="Introduction:Terminology:Component" type="section">
<index>1.7.7</index>
<name>Component</name>
<keywords>functional,human,collection,limit,define,include,transport,unit,source,interface</keywords>
<related>
<item>featureCarPlay:GeneralRequirements:Architecture:CarPlayOverUSB:CarPlayUSBNCMControlInterfaceDescriptorRequirements</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0015</internal>
</entry>
<entry label="Introduction:Terminology:Feature" type="section">
<index>1.7.8</index>
<name>Feature</name>
<keywords>possibility,react,account,recommendation,comply,design,specific,implement,requirement,associate</keywords>
<related>
<item>featureDevicePower:Usage</item>
<item>Introduction</item>
<item>Introduction:Terminology</item>
<item>featureCarPlay:GeneralRequirements:Architecture:CarPlayOverWireless:Session Establishment</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0016</internal>
</entry>
<entry label="Introduction:Terminology:USBDeviceandHostMode" type="section">
<index>1.7.9</index>
<name>USB Device Mode and USB Host Mode</name>
<keywords>usb device,usb host,capable,role</keywords>
<related>
<item>featureCarPlay:GeneralRequirements:Architecture:RoleSwitch</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0017</internal>
</entry>
<entry label="Introduction:Terminology:iAP" type="section">
<index>1.7.10</index>
<name>iAP</name>
<keywords>replacement,compose,compatible,ipod,protocol,complete,firmware,transport,connection,link</keywords>
<related>
<item>accessoryAll:iAP</item>
<item>transportBluetooth:TestProcedures:iAP</item>
<item>accessoryAll:OTATestingTISEISforUMTS</item>
<item>featureWAC:AppleDeviceInformationElement(IE):Structure</item>
<item>featureWAC:AppleDeviceInformationElement(IE)</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0018</internal>
</entry>
<entry label="Introduction:Terminology:DirectUserAction" type="section">
<index>1.7.11</index>
<name>Direct User Action</name>
<keywords>retry,extend,prohibit,direct,affect,observe,action,failure,certification,attach</keywords>
<related>
<item>accessoryKeyboards:TestProcedures:DirectUserAction</item>
<item>componentAuthCP20C:I2CProtocol</item>
<item>accessoryGameControllers:TestProcedures:ControlSurfaces:Joysticks</item>
<item>connectorE75:Modules</item>
<item>accessoryAll:OTATestingTISEISforUMTS</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0019</internal>
</entry>
<entry label="accessoryAll" type="chapter">
<index>2</index>
<name>All Accessories</name>
<keywords>initiative,matrix,modulation,test labs,radio frequency,display state,uncertainty,all bands,duplication</keywords>
<related>
<item>connectorE75:TestProcedures:AllAccessories</item>
<item>connectorE75:MechanicalRequirements:All</item>
<item>accessoryAll:RF</item>
<item>accessoryAll:TestProcedures:OTA:CTIATestLabs</item>
<item>accessoryAll:FeatureDuplication</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12CLK0020</internal>
</entry>
<entry label="accessoryAll:MinimumCompatibility" type="section">
<index>2.1</index>
<name>Minimum Apple Device Compatibility</name>
<keywords>exclusion,ipad devices,exclude,ipad air,compatibility,bug,fix,generation,claim</keywords>
<related>
<item>featureDevicePower:Requirements:ProvidingPowerToTheAppleDevice:AppleLightningConnectorsonPower-ProvidingAccessories</item>
<item>accessoryDocks</item>
<item>RevisionHistory:UpdatedContent</item>
<item>accessoryCases:TestProcedures:RequireAppleDeviceModels</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0022</internal>
</entry>
<entry label="accessoryAll:DevelopmentToolsAndEmulators" type="section">
<index>2.2</index>
<name>Development Tools and Emulators</name>
<keywords>development tools,emulator,emulate,prohibit,intend,create,expose,developer</keywords>
<related>
<item>accessoryAll:OTATestingTISEISforAllBands</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0023</internal>
</entry>
<entry label="accessoryAll:ReferenceDesignsAndDevelopmentKits" type="section">
<index>2.3</index>
<name>Reference Designs &amp; Development Kits</name>
<keywords>prototype,reference designs,development kits,audit,assist,framework,approach</keywords>
<related>
<item>moduleX90:SerialProtocol:ConfigurationPackets</item>
<item>transportBluetooth:Profiles:AudioVideoRemoteControlProfile:iOSAppProvidedMetadata</item>
<item>connectorE75:MechanicalRequirements:Cable:C48C68:CableTermination</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0024</internal>
</entry>
<entry label="accessoryAll:AccessoryAuthenticationandAccessoryIdentification" type="section">
<index>2.4</index>
<name>Accessory Authentication and Accessory Identification</name>
<keywords>charger,simple,accessory authentication,authenticate,accessory identification,sync,identify</keywords>
<related>
<item>moduleX533:I2CInterfaceAccessoryAuthenticationAndIdentification</item>
<item>featureAccessoryAuthentication:AccessoryAuthenticationExamples:TypicalAccessoryAuthentication</item>
<item>featureCarPlay:CarPlayCommunicationProtocol:ExampleInputReportLayoutForSimpleMedia</item>
<item>iAP2MessageParameterList:PowerUpdate</item>
<item>featureAccessoryIdentification:AccessoryIdentificationUsage:AccessoryIdentificationofPowerCapabilities</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0025</internal>
</entry>
<entry label="accessoryAll:iAP" type="section">
<index>2.5</index>
<name>iAP</name>
<keywords>nano,exact,identification,fall,compatibility,generation,claim,ipod,detect,detail</keywords>
<related>
<item>protocoliAP2:Link:Operation:Initialization</item>
<item>featureAccessoryIdentification</item>
<item>Introduction:Terminology:iAP</item>
<item>transportBluetooth:TestProcedures:iAP</item>
<item>referenceDeviceDimensionalDrawings:iPodnano:Drawing</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0026</internal>
</entry>
<entry label="accessoryAll:ConnectorModifications" type="section">
<index>2.6</index>
<name>Connector Modifications</name>
<keywords>modification,modify,direct,connector</keywords>
<related>
<item>transportUSB:TestProcedures:SI:FS:PassFailCriteria</item>
<item>transportUSB:TestProcedures:SI:HS:PassFailCriteria</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0027</internal>
</entry>
<entry label="accessoryAll:ConnectorAssemblies" type="section">
<index>2.7</index>
<name>Connector Assemblies</name>
<keywords>detachable,assembly,dongle,dock,case,define,implement,pin,connector,lightning</keywords>
<related>
<item>accessoryDocks</item>
<item>accessoryDongles</item>
<item>accessoryCases</item>
<item>transportUSB:DeviceMode:USBEmbeddedHost</item>
<item>accessoryAll:Attachments</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0028</internal>
</entry>
<entry label="accessoryAll:AdaptersAndProxies" type="section">
<index>2.8</index>
<name>Adapters and Proxies</name>
<keywords>proxy,facilitate,compliant,product,connection,apple,device</keywords>
<related>
<item>transportUSB:USBHostModePassthroughs</item>
<item>transportBluetooth:ConformityWithBluetoothSpecifications:ServiceDiscoveryProtocol</item>
<item>toolATS:ATSUtilityApp</item>
<item>accessoryAll:IntegratedUSBReceptacles</item>
<item>accessoryCases:Acoustics:SpeakerToMicrophoneCoupling</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0029</internal>
</entry>
<entry label="accessoryAll:Mixed30pinAndLightningConnectors" type="section">
<index>2.9</index>
<name>Mixed 30-pin and Lightning Connectors</name>
<keywords>multiplexer,lightning connectors,mixed,sufficient,accessible,integrity,approach,pin connector,charger,simple</keywords>
<related>
<item>connectorE75:ElectricalRequirements:SignalIntegrity</item>
<item>featureDevicePower:Requirements:ProvidingPowerToTheAppleDevice:MultipleConnectors</item>
<item>featureDigitalAudio</item>
<item>accessoryAll:Mixed30pinAndLightningConnectors:USBMux</item>
<item>accessoryAll:Mixed30pinAndLightningConnectors:SerialMux</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0034</internal>
</entry>
<entry label="accessoryAll:MixedHeadsetAndLightningConnectors" type="section">
<index>2.10</index>
<name>Mixed Headset Jack and Lightning Connectors</name>
<keywords>mixed headset jack,lightning connectors,attach,apple,device</keywords>
<related>
<item>accessoryAll:Mixed30pinAndLightningConnectors</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0035</internal>
</entry>
<entry label="accessoryAll:AppleUSBPowerAdapters" type="section">
<index>2.11</index>
<name>Apple USB Power Adapters</name>
<keywords>weight,outlet,apple usb power,wall,plug,support,device</keywords>
<related>
<item>featureDevicePower:TestProcedures:Charging</item>
<item>accessoryGameControllers:HIDRequirements:HIDGameControllerRequirements:ProductDesign:WeightAndBalance</item>
<item>accessoryGameControllers:HIDRequirements:HIDGameControllerRequirements:ProductDesign</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0036</internal>
</entry>
<entry label="accessoryAll:AppleWatchMagneticChargingCable" type="section">
<index>2.12</index>
<name>Apple Watch Magnetic Charging Cable</name>
<keywords>magnetic,watch,charge,claim,integrate,cable,supply,module,require,apple</keywords>
<related>
<item>moduleC62</item>
<item>moduleC62:TestProcedures:Electrical:ExternalUSBPowerSources:TestSetup</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0037</internal>
</entry>
<entry label="accessoryAll:AppleWatchLug" type="section">
<index>2.13</index>
<name>Apple Watch Lug</name>
<keywords>lug,distributor,guideline,accordance,watch,custom,integration,band,incorporate</keywords>
<related>
<item>AccessoryTestSystem:Overview:EquipmentList</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0038</internal>
</entry>
<entry label="accessoryAll:AppleDeviceDetection" type="section">
<index>2.14</index>
<name>Apple Device Detection</name>
<keywords>byte sequence,detection,assume,offer,respond,accessory power,implement,choose</keywords>
<related>
<item>connectorE75:ConnectorPadConfiguration</item>
<item>AppleLightningConnector:ComparisonWithThe30-pinConnector:AppleDeviceDetect</item>
<item>moduleX533:X533Module:APAccessory</item>
<item>connectorUltra:Connector</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0039</internal>
</entry>
<entry label="accessoryAll:MultipleSimultaneousiAP2Connections" type="section">
<index>2.15</index>
<name>Multiple Simultaneous iAP2 Connections</name>
<keywords>multiple simultaneous,determination,specific feature,same apple device,compare,shut,e.g.,wire</keywords>
<related>
<item>iAP2Message:DeviceUUIDUpdate</item>
<item>iAP2Message:BluetoothConnectionUpdate</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0040</internal>
</entry>
<entry label="accessoryAll:Disconnecting and Reconnecting" type="section">
<index>2.16</index>
<name>Disconnecting and Reconnecting</name>
<keywords>unplug,reconnect,disconnect,role,move,initiate,direct,range,physical,action</keywords>
<related>
<item>transportUSB:RoleSwitch</item>
<item>featureCarPlay</item>
<item>featureAccessoryPower:TestProcedures:Accessory Power and Device Power</item>
<item>transportBluetooth:TestProcedures:Reconnection:ReconnectfromAccessory</item>
<item>transportBluetooth:TestProcedures:Reconnection:ReconnectfromAppleDevice</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0041</internal>
</entry>
<entry label="accessoryAll:PresentationofAppleDeviceState" type="section">
<index>2.17</index>
<name>Presentation of Apple Device Updates</name>
<keywords>actuate,state change,presentation,hid usage,apple device updates,cache,happen,prohibit,inform,problem</keywords>
<related>
<item>protocolHID:HIDRequirements</item>
<item>transportBluetooth:Profiles:AudioVideoRemoteControlProfile:Notifications</item>
<item>featureMediaLibrary:MediaLibraryAccessUsage:MediaLibraryPlaybackUsage</item>
<item>featureAirPlay:AirPlayAccessoryUserInterface:MetadataPresentation:Metadatafield</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0043</internal>
</entry>
<entry label="accessoryAll:RelationshipsBetweenMultipleAccessories" type="section">
<index>2.18</index>
<name>Relationships Between Multiple Accessories</name>
<keywords>relationship,multiple accessories,responsible,behalf,individual,inactive,situation,manage,function</keywords>
<related>
<item>featureAirPlay:AccessoryComplianceTestPlanforAudioStreamingAccessories:SingleAudioStreamtoMultipleDevices(iTunes)Tests</item>
<item>CarPlay:CarPlayCommunicationProtocol:SetupAndControl:Synchronization:MediaClockSynchronization</item>
<item>transportBluetoothLowEnergy:Pairing</item>
<item>protocoliAP2:Sessions:ControlSession</item>
<item>moduleX533:I2CInterfaceAccessoryAuthenticationAndIdentification</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0044</internal>
</entry>
<entry label="accessoryAll:iBeacon" type="section">
<index>2.19</index>
<name>iBeacon</name>
<keywords>feature,support</keywords>
<related>
<item>iAP2MessageParameterList:NowPlayingUpdate</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0045</internal>
</entry>
<entry label="accessoryAll:FeatureDuplication" type="section">
<index>2.20</index>
<name>Feature Duplication</name>
<keywords>duplication,overlap,kind,midi,functionality,offer,addition,mechanism,feature,implement</keywords>
<related>
<item>accessoryAll</item>
<item>transportWiFi:TestProceduresfortheConsumers:OtherScenarios:Longevity</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0046</internal>
</entry>
<entry label="accessoryAll:TemperatureRange" type="section">
<index>2.21</index>
<name>Temperature Range</name>
<keywords>publish,temperature,equal,range,compatibility,claim,apple,device</keywords>
<related>
<item>componentAuthCP3.0:Mechanical:RecommendedOperatingConditions:Table</item>
<item>featureCarPlay:CarPlayCommunicationProtocol:UserInput</item>
<item>iAP2MessageParameterList:VehicleStatusUpdate</item>
<item>featureCarPlay:GeneralRequirements:Architecture:InterfaceConfiguration</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0047</internal>
</entry>
<entry label="accessoryAll:IntegratedUSBReceptacles" type="section">
<index>2.22</index>
<name>Integrated USB Receptacles</name>
<keywords>compliant,integrated,brand,receptacle,incorporate,purpose,comply,battery,detect,draw</keywords>
<related>
<item>featureDevicePower:Requirements:ProvidingPowerToTheAppleDevice:ConnectorsThatDoNotImplementiAP2</item>
<item>connectorC37</item>
<item>featureDevicePower:Requirements:ProvidingPowerToTheAppleDevice:ExternalPowerSource</item>
<item>accessoryDocks:FlexibleMechanism</item>
<item>accessoryAll:AdaptersAndProxies</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0048</internal>
</entry>
<entry label="accessoryAll:IntegratedNonUSBReceptacles" type="section">
<index>2.23</index>
<name>Integrated Non-USB Receptacles</name>
<keywords>included,thunderbolt,respective,hdmi,firewire,carry,highlight,compliant,accordance,integrated</keywords>
<related>
<item>transportUSB:DeviceMode:ConnectingMultipleAppleDevicesToMac</item>
<item>accessoryCables:All</item>
<item>componentMikeyTransmitter:Requirements</item>
<item>AirPlay:AccessoryComplianceTestPlanForAudioStreamingAccessories:AccessoryCommands(DACP)(iOS):Repeat/Shuffle:</item>
<item>AirPlay:AccessoryComplianceTestPlanForAudioStreamingAccessories:AccessoryCommands(DACP)(iTunes):Repeat/Shuffle:</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0049</internal>
</entry>
<entry label="accessoryAll:UserSuppliedCablesAndPowerSupplies" type="section">
<index>2.24</index>
<name>User Supplied Cables and Power Supplies</name>
<keywords>compliant connector,supplied cables,accommodate,clearance,surround,regard,power supplies,aspect</keywords>
<related>
<item>featureDevicePower:Requirements:ProvidingPowerToTheAppleDevice:ExternalPowerSource</item>
<item>featureCarPlay:GeneralRequirements:HardwareRequirements:HighResolutionDisplay</item>
<item>moduleTonberry:Mechanical</item>
<item>featureCarPlay:GeneralRequirements:MediaTypesandFormats:UserInterfaceStream:Resolution</item>
<item>accessoryCables:Headset:MikeyBusAccessory</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0051</internal>
</entry>
<entry label="accessoryAll:RemovableStorage" type="section">
<index>2.25</index>
<name>Removable Storage</name>
<keywords>removable,reader,dakota,storage,card,external accessory protocol,integrate,component</keywords>
<related>
<item>featureExternalAccessoryProtocol</item>
<item>connectorHeadsetPlug:TestProcedures</item>
<item>accessoryAll:Attachments</item>
<item>componentTriStar:Mechanical:RecommendedHandling</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0052</internal>
</entry>
<entry label="accessoryAll:TDMANoise" type="section">
<index>2.26</index>
<name>TDMA Noise</name>
<keywords>division,chopper,couple,electronics,radiate,produce,interference,audible,emit,conduct</keywords>
<related>
<item>featureDigitalAudio:DigitalAudioRequirements</item>
<item>accessoryHeadsets</item>
<item>accessoryCases:AcousticsCouplingFromImproperCaseSeal</item>
<item>connector30Pin:ConnectorDescriptions:MidPlaneFrictionPlug</item>
<item>connector30Pin:ConnectorDescriptions:MidPlanePlug</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0053</internal>
</entry>
<entry label="accessoryAll:Attachments" type="section">
<index>2.27</index>
<name>Attachments</name>
<keywords>barcode,scanner,credit,desk,case accessory,mat,reader,detachable,attachment,card</keywords>
<related>
<item>accessoryAll:OTA</item>
<item>accessoryAll:ConnectorAssemblies</item>
<item>transportUSB:DeviceMode:USBEmbeddedHost</item>
<item>accessoryAll:RemovableStorage</item>
<item>accessoryAirPodsAttachments:Interference</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0054</internal>
</entry>
<entry label="accessoryAll:MagneticInterference" type="section">
<index>2.28</index>
<name>Magnetic Interference</name>
<keywords>recalibration,magnetometer,autofocus,optical,metal components,digital compass,equip</keywords>
<related>
<item>accessoryCovers:MagneticInterference</item>
<item>accessoryCases:MagneticInterference</item>
<item>accessoryCameraAttachments:MagneticInterference</item>
<item>RevisionHistory:UpdatedContent</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0055</internal>
</entry>
<entry label="accessoryAll:RF" type="section">
<index>2.29</index>
<name>Radio Frequency (RF) Performance</name>
<keywords>radio frequency,coating,nfc,recommendation,performance,antenna,material,air</keywords>
<related>
<item>accessoryAll</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0056</internal>
</entry>
<entry label="accessoryAll:MaterialsCoatings" type="section">
<index>2.29.1</index>
<name>Materials and Coatings</name>
<keywords>deposition,magnesium,titanium,dioxide,carbon,paint,plate,metallic,coating,absorb</keywords>
<related>
<item>accessoryAll:AntennaKeepOut</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0057</internal>
</entry>
<entry label="accessoryAll:AntennaKeepOut" type="section">
<index>2.29.2</index>
<name>Antenna Keep-Out</name>
<keywords>absorb,antenna keep,coating,region,risk,energy,device dimensional drawings,material,metal</keywords>
<related>
<item>accessoryAll:MaterialsCoatings</item>
<item>referenceDeviceDimensionalDrawings</item>
<item>accessoryAll:OTA</item>
<item>accessoryAll:NFC</item>
<item>connectorE75:TestProcedures:DockAccessories:DockShieldBendTest:Clamp</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0058</internal>
</entry>
<entry label="accessoryAll:OTA" type="section">
<index>2.29.3</index>
<name>Over The Air (OTA)</name>
<keywords>quantify,operating bands,intrude,attachment,effective,degrade,radiate,efficiency,sensitivity,reception</keywords>
<related>
<item>accessoryAll:Attachments</item>
<item>accessoryAll:AntennaKeepOut</item>
<item>accessoryAll:NFC</item>
<item>accessoryAll:TestProcedures:OTA:Terminology</item>
<item>accessoryAirPodsAttachments</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0059</internal>
</entry>