<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE spec [
    <!ELEMENT spec (auxfiles?, name, shortname?, toc)>
    <!ATTLIST spec id CDATA #REQUIRED>
    <!ATTLIST spec variant CDATA #REQUIRED>
    <!ATTLIST spec revision CDATA #REQUIRED>
    <!ATTLIST spec lang CDATA #REQUIRED>
    <!ATTLIST spec version CDATA #REQUIRED>
    <!ATTLIST spec nopreviews CDATA #IMPLIED>
    <!ATTLIST spec xmlns CDATA #FIXED "http://apple.com/ns/spec/v1">
    <!ATTLIST spec accsys CDATA #FIXED "http://apple.com/ns/accsys/v1">
    <!ELEMENT auxfiles (file)*>
    <!ELEMENT file EMPTY>
    <!ATTLIST file type CDATA #FIXED "pdf">
    <!ATTLIST file verifier CDATA #REQUIRED>
    <!ATTLIST file read-info CDATA #IMPLIED>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT shortname (#PCDATA)>
    <!ELEMENT toc (entry)+>
    <!ELEMENT entry (index, name, keywords?, related*, internal?)>
    <!ATTLIST entry label CDATA #REQUIRED>
    <!ATTLIST entry type (section|chapter|figure|table) "section">
    <!ELEMENT index (#PCDATA)>
    <!ELEMENT internal (#PCDATA)>
    <!ELEMENT related (item)*>
    <!ELEMENT item (#PCDATA)>
    <!ELEMENT keywords (#PCDATA)>
]>
<spec revision="28" id="aispec" lang="en-US" accsys="http://apple.com/ns/accsys/v1" nopreviews="0" variant="release" version="1" xmlns="http://apple.com/ns/spec/v1">
<auxfiles>
<file type="pdf" verifier="Accessory,Interface,Specification,Release,R28" read-info="52.0,42.0,508.0,700.0">
</file>
</auxfiles>
<name>Accessory Interface Specification R28</name>
<shortname>
</shortname>
<toc>
<entry label="Introduction" type="chapter">
<index>1</index>
<name>Introduction</name>
<keywords>aforementioned,cryptography,possibility,computation,challenging,implication,prohibition,explicitly,television,historical</keywords>
<related>
<item>spec://featureAirPlay:Introduction/*</item>
<item>spec://I2CRegisterParameterList:componentAuthCP3.0:AuthenticationControlandStatus:WriteOnlyBits/*</item>
<item>spec://Introduction:Requirements/*</item>
<item>spec://Introduction:Terminology/*</item>
<item>spec://Introduction:Terminology:AccessoryDeviceProduct/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11CLK0001</internal>
</entry>
<entry label="Introduction:Purpose" type="section">
<index>1.1</index>
<name>Purpose of This Specification</name>
<keywords>introduction,recommendation,purpose,detail,requirement,interface,connector,apple,device</keywords>
<related>
<item>spec://Introduction:Terminology:Component/*</item>
<item>spec://Introduction:Terminology:ChallengeResponse/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
<item>spec://Introduction:Terminology:iAP/*</item>
<item>spec://Introduction:Organization/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0002</internal>
</entry>
<entry label="Introduction:Organization" type="section">
<index>1.2</index>
<name>Organization</name>
<keywords>introduction,related,chapter,tool,group,part,component,feature,module,connector</keywords>
<related>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
<item>spec://Introduction:Terminology:ChallengeResponse/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
<item>spec://transportUSB:HostMode:Enumeration/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0003</internal>
</entry>
<entry label="Introduction:Applicability" type="section">
<index>1.3</index>
<name>Applicability</name>
<keywords>trackpad,magic,accessory interface,apple watch series,introduction,1st generation,4th generation</keywords>
<related>
<item>spec://referenceDeviceDimensionalDrawings:iPadWiFi4thGen:Drawing/*</item>
<item>spec://accessoryCases:J99RequiredTestingTable/*</item>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
<item>spec://Introduction:Terminology:ChallengeResponse/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0004</internal>
</entry>
<entry label="Introduction:Requirements" type="section">
<index>1.4</index>
<name>Requirements, Recommendations, and Permissions</name>
<keywords>implication,prohibition,historical,statement,encourage,permission,understand,introduction,licensee</keywords>
<related>
<item>spec://Introduction/*</item>
<item>spec://featureAccessoryPower:Usage:EnteringIntermittentHighPowerMode/*</item>
<item>spec://featureAirPlay:AirPlaySetupExperience/*</item>
<item>spec://featureCarPlay:GeneralRequirements:Architecture:CarPlayOverWireless:Frequency%20Bands/*</item>
<item>spec://Introduction:Terminology:AccessoryDeviceProduct/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0005</internal>
</entry>
<entry label="Introduction:DeveloperPreview" type="section">
<index>1.5</index>
<name>Developer Preview</name>
<keywords>adoption,licensed,introduction,preview,final,accuracy,developer,propose,development</keywords>
<related>
<item>spec://Introduction:ManufacturerPreview/*</item>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
<item>spec://Introduction:Terminology:ChallengeResponse/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0006</internal>
</entry>
<entry label="Introduction:ManufacturerPreview" type="section">
<index>1.6</index>
<name>Manufacturer Preview</name>
<keywords>introduction,preview,develop,license,propose,final,manufacturer,developer,content</keywords>
<related>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
<item>spec://Introduction:Terminology:ChallengeResponse/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
<item>spec://Introduction:Terminology:iAP/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0007</internal>
</entry>
<entry label="Introduction:Terminology" type="section">
<index>1.7</index>
<name>Terminology</name>
<keywords>aforementioned,cryptography,computation,challenging,possibility,television,explicitly,creation,watchos,philip</keywords>
<related>
<item>spec://accessoryAll:TestProcedures:OTA:Terminology/*</item>
<item>spec://I2CRegisterParameterList:componentAuthCP3.0:AuthenticationControlandStatus:WriteOnlyBits/*</item>
<item>spec://Introduction:Terminology:AccessoryDeviceProduct/*</item>
<item>spec://Introduction/*</item>
<item>spec://Introduction:Terminology:Challenge/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0008</internal>
</entry>
<entry label="Introduction:Terminology:AccessoryDeviceProduct" type="section">
<index>1.7.1</index>
<name>Accessory, Device, and Product</name>
<keywords>aforementioned,explicitly,television,watchos,introduction,term,statement,mobile,refer</keywords>
<related>
<item>spec://Introduction:Terminology/*</item>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
<item>spec://Introduction:Terminology:ChallengeResponse/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0009</internal>
</entry>
<entry label="Introduction:Terminology:AuthenticationCoprocessor" type="section">
<index>1.7.2</index>
<name>Authentication Coprocessor</name>
<keywords>creation,philip,introduction,al,related,reside,easy,signature,document,locate</keywords>
<related>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Organization/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
<item>spec://Introduction:Terminology:ChallengeResponse/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0010</internal>
</entry>
<entry label="Introduction:Terminology:I2CBus" type="section">
<index>1.7.3</index>
<name>I^{2}C Bus</name>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0011</internal>
</entry>
<entry label="Introduction:Terminology:Challenge" type="section">
<index>1.7.4</index>
<name>Challenge</name>
<keywords>challenging,computation,introduction,vice,random,verification,offer,result,return,perform</keywords>
<related>
<item>spec://I2CRegisterParameterList:componentAuthCP3.0:AuthenticationControlandStatus:WriteOnlyBits/*</item>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:ChallengeResponse/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0012</internal>
</entry>
<entry label="Introduction:Terminology:ChallengeResponse" type="section">
<index>1.7.5</index>
<name>Challenge Response</name>
<keywords>introduction,obtain,offer,challenge,result,response,process,perform,page</keywords>
<related>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
<item>spec://Introduction:Terminology:iAP/*</item>
<item>spec://Introduction:Organization/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0013</internal>
</entry>
<entry label="Introduction:Terminology:X509Certificate" type="section">
<index>1.7.6</index>
<name>X.509 Certificate</name>
<keywords>cryptography,introduction,govern,telecommunication,international,identity,union,public,certificarsi,verification</keywords>
<related>
<item>spec://featureCarPlay:GeneralRequirements:MediaTypesandFormats:Audio:Telephony/*</item>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
<item>spec://Introduction:Terminology:ChallengeResponse/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0014</internal>
</entry>
<entry label="Introduction:Terminology:Component" type="section">
<index>1.7.7</index>
<name>Component</name>
<keywords>introduction,functional,human,collection,limit,data,define,include,unit,interface</keywords>
<related>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:ChallengeResponse/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
<item>spec://Introduction:Terminology:iAP/*</item>
<item>spec://Introduction:Organization/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0015</internal>
</entry>
<entry label="Introduction:Terminology:DUA" type="section">
<index>1.7.8</index>
<name>Direct User Action</name>
<keywords>grant,actuate,introduction,wave,retry,prohibit,extend,task,interact,direct</keywords>
<related>
<item>spec://featureCarPlay:GeneralRequirements:Architecture:CarPlayOverWireless:Session%20Termination:Direct%20User%20Action/*</item>
<item>spec://accessoryKeyboards:TestProcedures:DirectUserAction/*</item>
<item>spec://accessoryAll:PresentationofAppleDeviceState/*</item>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0016</internal>
</entry>
<entry label="Introduction:Terminology:Feature" type="section">
<index>1.7.9</index>
<name>Feature</name>
<keywords>possibility,introduction,react,account,recommendation,comply,design,specific,implement,requirement</keywords>
<related>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
<item>spec://Introduction:Terminology:ChallengeResponse/*</item>
<item>spec://Introduction:Terminology:USBDeviceandHostMode/*</item>
<item>spec://Introduction:Terminology:iAP/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0017</internal>
</entry>
<entry label="Introduction:Terminology:USBDeviceandHostMode" type="section">
<index>1.7.10</index>
<name>USB Device Mode and USB Host Mode</name>
<keywords>introduction,usb host,usb device,capable,role</keywords>
<related>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
<item>spec://Introduction:Terminology:ChallengeResponse/*</item>
<item>spec://Introduction:Terminology:iAP/*</item>
<item>spec://Introduction:Organization/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0018</internal>
</entry>
<entry label="Introduction:Terminology:iAP" type="section">
<index>1.7.11</index>
<name>iAP</name>
<keywords>introduction,replacement,compatible,ipod,protocol,firmware,complete</keywords>
<related>
<item>spec://accessoryAll:iAP/*</item>
<item>spec://transportBluetooth:TestProcedures:iAP/*</item>
<item>spec://Introduction:Purpose/*</item>
<item>spec://Introduction:Terminology:Component/*</item>
<item>spec://Introduction:Terminology:ChallengeResponse/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH11-BK42CH11SLK0019</internal>
</entry>
<entry label="accessoryAll" type="chapter">
<index>2</index>
<name>All Accessories</name>
<keywords>radio frequency,integrated usb receptacles,duplication,matrix,connector modifications,uncertainty,multiple simultaneous,determination</keywords>
<related>
<item>spec://connectorE75:TestProcedures:AllAccessories/*</item>
<item>spec://connectorE75:MechanicalRequirements:All/*</item>
<item>spec://accessoryAll:FeatureDuplication/*</item>
<item>spec://accessoryAll:MultipleSimultaneousiAP2Connections/*</item>
<item>spec://accessoryAll:RF/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12CLK0020</internal>
</entry>
<entry label="accessoryAll:MinimumCompatibility" type="section">
<index>2.1</index>
<name>Minimum Apple Device Compatibility</name>
<keywords>exclusion,ipad devices,exclude,compatibility,bug,ipad pro,6th,generation</keywords>
<related>
<item>spec://componentAuthCP20C:DeviceCharacteristics:DCElectricalCharacteristics/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0022</internal>
</entry>
<entry label="accessoryAll:DevelopmentToolsAndEmulators" type="section">
<index>2.2</index>
<name>Development Tools and Emulators</name>
<keywords>development tools,emulator,prohibit,emulate,intend,developer,create,expose</keywords>
<related>
<item>spec://accessoryAll:OTATestingTISEISforAllBands/*</item>
<item>spec://accessoryAll:TestProcedures:OTA:Procedure/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0023</internal>
</entry>
<entry label="accessoryAll:ReferenceDesignsAndDevelopmentKits" type="section">
<index>2.3</index>
<name>Reference Designs &amp; Development Kits</name>
<keywords>prototype,reference designs,development kits,audit,assist,framework,approach</keywords>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0024</internal>
</entry>
<entry label="accessoryAll:AccessoryAuthenticationandAccessoryIdentification" type="section">
<index>2.4</index>
<name>Accessory Authentication and Accessory Identification</name>
<keywords>simple,charger,accessory authentication,accessory identification,authenticate,sync,identify</keywords>
<related>
<item>spec://featureCarPlay:CarPlayCommunicationProtocol:ExampleInputReportLayoutForSimpleMedia/*</item>
<item>spec://moduleX533:I2CInterfaceAccessoryAuthenticationAndIdentification/*</item>
<item>spec://featureAccessoryAuthentication:Examples:TypicalAccessoryAuthentication/*</item>
<item>spec://moduleX890:Power:Module/*</item>
<item>spec://protocolHID:Requirements:HIDNativeTransport(Bluetooth)/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0025</internal>
</entry>
<entry label="accessoryAll:iAP" type="section">
<index>2.5</index>
<name>iAP</name>
<keywords>identification,fall,exact,detect,implement,detail,support,present,information,note</keywords>
<related>
<item>spec://Introduction:Terminology:iAP/*</item>
<item>spec://transportBluetooth:TestProcedures:iAP/*</item>
<item>spec://featureAccessoryIdentification:Examples:TypicalAccessoryIdentification/*</item>
<item>spec://referenceiAP2Messages:AccessoryIdentification/*</item>
<item>spec://transportUSB:TestProcedures:SI:HS:PassFailCriteriaHUT/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0027</internal>
</entry>
<entry label="accessoryAll:ConnectorModifications" type="section">
<index>2.6</index>
<name>Connector Modifications</name>
<keywords>modification,modify,direct,connector</keywords>
<related>
<item>spec://transportUSB:TestProcedures:SI:HS:PassFailCriteria/*</item>
<item>spec://transportUSB:TestProcedures:SI:FS:PassFailCriteria/*</item>
<item>spec://transportUSB:TestProcedures/*</item>
<item>spec://transportUSB:TestProcedures:SI:FS/*</item>
<item>spec://transportUSB:TestProcedures:SI:HS/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0028</internal>
</entry>
<entry label="accessoryAll:ConnectorAssemblies" type="section">
<index>2.7</index>
<name>Connector Assemblies</name>
<keywords>detachable,assembly,dongle,dock,case,define,implement,connector,lightning,page</keywords>
<related>
<item>spec://moduleX890:ConnectionMethods/*</item>
<item>spec://transportUSB:DeviceMode:USBEmbeddedHost/*</item>
<item>spec://accessoryDongles:E75Dongles/*</item>
<item>spec://accessoryGameControllers:HIDRequirements:HIDGameControllerRequirements:SwitchesAndPositionEncoders/*</item>
<item>spec://accessoryDongles:ProductDesign/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0029</internal>
</entry>
<entry label="accessoryAll:AdaptersAndProxies" type="section">
<index>2.8</index>
<name>Adapters and Proxies</name>
<keywords>proxy,facilitate,compliant,product,connection,apple,device</keywords>
<related>
<item>spec://transportBluetooth::ServiceDiscoveryProtocol/*</item>
<item>spec://transportUSB:USBHostModePassthroughs/*</item>
<item>spec://toolATS:CertificationAssistant/*</item>
<item>spec://accessoryCases:Acoustics:SpeakerToMicrophoneCoupling/*</item>
<item>spec://accessoryDocks:FlexibleMechanism/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0030</internal>
</entry>
<entry label="accessoryAll:MixedHeadsetAndLightningConnectors" type="section">
<index>2.9</index>
<name>Mixed Headset Jack and Lightning Connectors</name>
<keywords>mixed headset jack,lightning connectors,attach,apple,device</keywords>
<related>
<item>spec://featureDevicePower:TestProcedures:AccessoryPowerSources:OutputVoltageRegulation/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0031</internal>
</entry>
<entry label="accessoryAll:AppleUSBPowerAdapters" type="section">
<index>2.10</index>
<name>Apple USB Power Adapters</name>
<keywords>apple usb power,outlet,weight,wall,plug,support,device</keywords>
<related>
<item>spec://featureDevicePower:TestProcedures:Charging/*</item>
<item>spec://accessoryGameControllers:HIDRequirements:HIDGameControllerRequirements:ProductDesign:WeightAndBalance/*</item>
<item>spec://accessoryGameControllers:HIDRequirements:HIDGameControllerRequirements:ProductDesign/*</item>
<item>spec://accessoryGameControllers/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0032</internal>
</entry>
<entry label="accessoryAll:AppleWatchMagneticChargingCable" type="section">
<index>2.11</index>
<name>Apple Watch Magnetic Charging Cable</name>
<keywords>magnetic,watch,charge,integrate,claim,cable,module,supply,require,apple</keywords>
<related>
<item>spec://moduleC62:Magnetic%20Charging%20Module/*</item>
<item>spec://moduleC62:TestProcedures:Electrical:ExternalUSBPowerSources:TestSetup/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0033</internal>
</entry>
<entry label="accessoryAll:AppleWatchLug" type="section">
<index>2.12</index>
<name>Apple Watch Lug</name>
<keywords>lug,distributor,guideline,accordance,watch,custom,integration,band,incorporate</keywords>
<related>
<item>spec://AccessoryTestSystem:Overview:EquipmentList/*</item>
<item>spec://toolATS:Overview/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0034</internal>
</entry>
<entry label="accessoryAll:AppleDeviceDetection" type="section">
<index>2.13</index>
<name>Apple Device Detection</name>
<keywords>byte sequence,detection,assume,accessory power,offer,respond,integrate,implement,choose</keywords>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0035</internal>
</entry>
<entry label="accessoryAll:MultipleSimultaneousiAP2Connections" type="section">
<index>2.14</index>
<name>Multiple Simultaneous iAP2 Connections</name>
<keywords>multiple simultaneous,determination,specific feature,compare,same apple device,shut,transport,e.g.</keywords>
<related>
<item>spec://accessoryAll/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0036</internal>
</entry>
<entry label="accessoryAll:Disconnecting and Reconnecting" type="section">
<index>2.15</index>
<name>Disconnecting and Reconnecting</name>
<keywords>reconnect,disconnect,role,initiate,direct,action,connection,case,switch,carplay</keywords>
<related>
<item>spec://transportBluetooth:TestProcedures:Reconnection:ReconnectfromAccessory/*</item>
<item>spec://transportBluetooth:TestProcedures:Reconnection:ReconnectfromAppleDevice/*</item>
<item>spec://featureCarPlay:GeneralRequirements:Architecture:CarPlayOverWireless:Session%20Termination:Direct%20User%20Action/*</item>
<item>spec://protocoliAP2:Link:Operation:Reset/*</item>
<item>spec://featureCarPlay:GeneralRequirements:Architecture:CarPlayOverWireless:Session%20Termination/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0037</internal>
</entry>
<entry label="accessoryAll:PresentationofAppleDeviceState" type="section">
<index>2.16</index>
<name>Presentation of Apple Device Updates</name>
<keywords>state change,actuate,hid usage,presentation,apple device updates,cache,prohibit,inform,happen,problem</keywords>
<related>
<item>spec://Introduction:Terminology:DUA/*</item>
<item>spec://transportBluetooth:Profiles:AudioVideoRemoteControlProfile:Notifications/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0039</internal>
</entry>
<entry label="accessoryAll:RelationshipsBetweenMultipleAccessories" type="section">
<index>2.17</index>
<name>Relationships Between Multiple Accessories</name>
<keywords>multiple accessories,relationship,responsible,behalf,individual,situation,inactive,manage,component</keywords>
<related>
<item>spec://featureAirPlay:AccessoryComplianceTestPlanforAudioStreamingAccessories:SingleAudioStreamtoMultipleDevices(iTunes)Tests/*</item>
<item>spec://CarPlay:CarPlayCommunicationProtocol:SetupAndControl:Synchronization:MediaClockSynchronization/*</item>
<item>spec://featureOutOfBandBluetoothPairing:Usage/*</item>
<item>spec://featureCarPlay:CarPlayCommunicationProtocol:SetupandControl:Synchronization/*</item>
<item>spec://featureOutOfBandBluetoothPairing/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0040</internal>
</entry>
<entry label="accessoryAll:iBeacon" type="section">
<index>2.18</index>
<name>iBeacon</name>
<keywords>feature,support</keywords>
<related>
<item>spec://iAP2MessageParameterList:NowPlayingUpdate/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0041</internal>
</entry>
<entry label="accessoryAll:FeatureDuplication" type="section">
<index>2.19</index>
<name>Feature Duplication</name>
<keywords>duplication,overlap,kind,midi,functionality,offer,addition,mechanism,feature,implement</keywords>
<related>
<item>spec://accessoryAll/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0042</internal>
</entry>
<entry label="accessoryAll:TemperatureRange" type="section">
<index>2.20</index>
<name>Temperature Range</name>
<keywords>publish,temperature,range,equal,compatibility,claim,apple,device</keywords>
<related>
<item>spec://componentAuthCP3.0:RecommendedOperatingConditions:Table/*</item>
<item>spec://componentAuthCP3.0:MaximumOperatingConditions:Table/*</item>
<item>spec://componentAuthCP20C:DeviceCharacteristics:MaximumOperatingConditions:Table/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0043</internal>
</entry>
<entry label="accessoryAll:IntegratedUSBReceptacles" type="section">
<index>2.21</index>
<name>Integrated USB Receptacles</name>
<keywords>benefit,bundled cables,silicon,usb power,bundled usb,usb battery charging,certify,brick</keywords>
<related>
<item>spec://accessoryAll:USBCReceptacle:Bundled%20Cables%20and%20Power%20Adapters/*</item>
<item>spec://accessoryAll:USBCReceptacle/*</item>
<item>spec://connectorC37:Electrical/*</item>
<item>spec://accessoryAll:USBCReceptacle:Test%20Procedures/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0044</internal>
</entry>
<entry label="accessoryAll:USBCReceptacle" type="section">
<index>2.21.1</index>
<name>USB-C Receptacle</name>
<keywords>benefit,bundled cables,silicon,usb power,bundled usb,certify,brick</keywords>
<related>
<item>spec://accessoryAll:USBCReceptacle:Bundled%20Cables%20and%20Power%20Adapters/*</item>
<item>spec://accessoryAll:IntegratedUSBReceptacles/*</item>
<item>spec://accessoryAll:USBCReceptacle:Test%20Procedures/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0045</internal>
</entry>
<entry label="accessoryAll:USBCReceptacle:Mechanical" type="section">
<index>2.21.1.1</index>
<name>Mechanical</name>
<keywords>certify,integrated,receptacle,id,usb,connector,test</keywords>
<related>
<item>spec://moduleC101P:Mechanical/*</item>
<item>spec://moduleC100P:Mechanical/*</item>
<item>spec://moduleX533:Mechanical/*</item>
<item>spec://componentAuthCP3.0:Mechanical/*</item>
<item>spec://moduleC62:TestProcedures:Mechanical/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0046</internal>
</entry>
<entry label="accessoryAll:USBCReceptacle:Electrical" type="section">
<index>2.21.1.2</index>
<name>Electrical</name>
<keywords>silicon,usb power delivery,certify,enumerate,dedicated,identify,resistor,integrated,brand</keywords>
<related>
<item>spec://componentTriStar:Electrical/*</item>
<item>spec://componentMikeyController:Electrical/*</item>
<item>spec://moduleC62:Electrical/*</item>
<item>spec://componentAuthCP3.0:Electrical/*</item>
<item>spec://moduleX533:TestProcedures:Electrical/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0047</internal>
</entry>
<entry label="accessoryAll:USBCReceptacle:Bundled Cables and Power Adapters" type="section">
<index>2.21.1.3</index>
<name>Bundled Cables and Power Adapters</name>
<keywords>bundled cables,brick,assign,integrated,incorporate,receptacle,id,usb</keywords>
<related>
<item>spec://accessoryAll:USBCReceptacle/*</item>
<item>spec://accessoryAll:IntegratedUSBReceptacles/*</item>
<item>spec://AccessoryTestSystem:HardwareConsiderations:ATSLightningBoxWithoutUSBTraffic/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0048</internal>
</entry>
<entry label="accessoryAll:USBCReceptacle:Test Procedures" type="section">
<index>2.21.1.4</index>
<name>Test Procedures</name>
<keywords>usb power,bundled usb,applicable,identify,party,integrated,brand,equipment</keywords>
<related>
<item>spec://featureNowPlaying:TestProcedures/*</item>
<item>spec://featureAssistiveTouchPointer:TestProcedures/*</item>
<item>spec://accessoryGameControllers:TestProcedures/*</item>
<item>spec://featureAssistiveSwitchControl:TestProcedures/*</item>
<item>spec://featureExternalAccessoryProtocol:TestProcedures/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0049</internal>
</entry>
<entry label="accessoryAll:IntegratedNonUSBReceptacles" type="section">
<index>2.22</index>
<name>Integrated Non-USB Receptacles</name>
<keywords>included,hdmi,thunderbolt,respective,carry,compliant,firewire,highlight,manner,accordance</keywords>
<related>
<item>spec://transportUSB:DeviceMode:ConnectingMultipleAppleDevicesToMac/*</item>
<item>spec://accessoryCables:All/*</item>
<item>spec://componentMikeyTransmitter:Requirements/*</item>
<item>spec://connectorE75:ElectricalRequirements:Shielding/*</item>
<item>spec://transportUSB:DeviceMode/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0050</internal>
</entry>
<entry label="accessoryAll:UserSuppliedCablesAndPowerSupplies" type="section">
<index>2.23</index>
<name>User Supplied Cables and Power Supplies</name>
<keywords>regard,compliant connector,supplied cables,clearance,surround,accommodate,sufficient,power supplies</keywords>
<related>
<item>spec://featureCarPlay:GeneralRequirements:HardwareRequirements:HighResolutionDisplay/*</item>
<item>spec://moduleTonberry:Mechanical/*</item>
<item>spec://featureAirPlay:AirPlayAccessoryRequirements:CertificationRequirements/*</item>
</related>
<internal>//apple_ref/doc/uid/DontLinkBookID_1-BK42CH12-BK42CH12SLK0052</internal>
</entry>
<entry label="accessoryAll:RemovableStorage" type="section">
<index>2.24</index>
<name>Removable Storage</name>
<keywords>removable,reader,dakota,storage,card,external accessory protocol,integrate,component</keywords>
<related>
<item>spec://connectorHeadsetPlug:TestProcedures/*</item>
<item>spec://connectorHeadsetPlug/*</item>
<item>spec://accessoryAll:Attachments/*</item>
<item>spec://featureExternalAccessoryProtocol:TestProcedures:ExternalAccessoryProtocoloverNative/*</item>
</related>